### ISSUE TITLE
Brightness Indicator doesn't show when changing

### ISSUE THREAD

**Issue by totallynotd** [wad11656/Restore-Boot-Camp-Brightness-Keys#2]
title says it all

**Comment by wad11656** [comment]
Unfortunately the screen died on the laptop I used this app for, so I can't verify this is a consistent issue or test a potential fix.

@qwerty12, who is the creator of [LaptopBrightnessSetter](https://github.com/qwerty12/AutoHotkeyScripts/tree/master/LaptopBrightnessSetter) (which is where I got that part of my code) calls the brightness slider/indicator the "OSD" (on-screen display). He admits in the README that it may be unreliable:
> Showing the OSD might be a bit iffy

I've had it disappear on me, too.

**I think tapping on the volume buttons to bring up the OSD "wakes up" this functionality. Try hitting the volume buttons then immediately on the brightness buttons.**

If a PC restart doesn't fix it, try running the uninstaller from the install directory, then reinstall the newest [release](https://github.com/wad11656/Restore-Boot-Camp-Brightness-Keys/releases).

If it's consistently not working, I believe the `0x37` would need to be updated in the below section of [qwerty12's code](https://gist.github.com/qwerty12/4b3f41eb61724cd9e8f2bb5cc15c33c2):

```ahk
_ShowBrightnessOSD()
{
	static PostMessagePtr := DllCall("GetProcAddress", "Ptr", DllCall("GetModuleHandle", "Str", "user32.dll", "Ptr"), "AStr", A_IsUnicode ? "PostMessageW" : "PostMessageA", "Ptr")
		  ,WM_SHELLHOOK := DllCall("RegisterWindowMessage", "Str", "SHELLHOOK", "UInt")
	if A_OSVersion in WIN_VISTA,WIN_7
		return
	BrightnessSetter._RealiseOSDWindowIfNeeded()
	; Thanks to YashMaster @ https://github.com/YashMaster/Tweaky/blob/master/Tweaky/BrightnessHandler.h for realising this could be done:
	if (BrightnessSetter._osdHwnd)
		DllCall(PostMessagePtr, "Ptr", BrightnessSetter._osdHwnd, "UInt", WM_SHELLHOOK, "Ptr", 0x37, "Ptr", 0)
}
```

@qwerty12's code uses a fallback of rapidly muting/unmuting the volume to try to bring up the volume & brightness OSD/slider. I think that's maybe why hitting the volume buttons, then the brightness buttons, seems to help "wake up" the below part of his code...at least for me:

> To create the [OSD] if needed, [my code] [...] falls back to quickly muting/unmuting the volume.

```ahk
_RealiseOSDWindowIfNeeded()
{
	...
	if (!DllCall(IsWindow, "Ptr", BrightnessSetter._osdHwnd) && !BrightnessSetter._FindAndSetOSDWindow()) {
		...
		}
		; who knows if the SID & IID above will work for future versions of Windows 10 (or Windows 8). Fall back to this if needs must
		Loop 2 {
			SendEvent {Volume_Mute 2}
			if (BrightnessSetter._FindAndSetOSDWindow())
				return
			Sleep 100
		}
	}
}
```
